// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://owfbexzbsteipbogncyq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im93ZmJleHpic3RlaXBib2duY3lxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc2OTc2MTUsImV4cCI6MjA3MzI3MzYxNX0.zv49IKeSfOBHm6sEsaF4hom7p83hYq7nMeS12wl408U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});